export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_POSTS_START = 'GET_START'
export const GET_POSTS_SUCCESS = 'GET_SUCCESS'
export const GET_POSTS_FAIL = 'GET_FAIL'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const SAVE_POST_START = 'SAVE_POST_START'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL'

export const GET_POST_TO_UPDATE_START = 'GET_POST_TO_UPDATE_START'
export const GET_POST_TO_UPDATE_SUCCESS = 'GET_POST_TO_UPDATE_SUCCESS'
export const GET_POST_TO_UPDATE_FAIL = 'GET_POST_TO_UPDATE_FAIL'

export const UPDATE_POST_START = 'UPDATE_POST_START'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
