//POST CREATE
export const SAVE_POST_LOADING = 'SAVE_POST_LOADING'
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'

export const UPDATE_POST_LOADING = 'UPDATE_POST_LOADING'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

export const GET_POST_TO_UPDATE_LOADING = 'GET_POST_TO_UPDATE_LOADING'
export const GET_POST_TO_UPDATE_SUCCESS = 'GET_POST_TO_UPDATE_SUCCESS'
export const GET_POST_TO_UPDATE_FAIL = 'GET_POST_TO_UPDATE_FAIL'



// POST LIST
export const GET_POST_LOADING = 'GET_POSTS_LOADING'
export const GET_POSTS_SUCCESS= 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL= 'GET_POSTS_FAIL'

export const DELETE_POST_LOADING = 'DELETE_POST_LOADING'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'


